export KSC_REPO_PATH="$HOME/ksc-cli"
export KSC_DIR="$HOME/.ksc"
export KSC_CONFIG_FILES="$HOME/config-files"
export KSC_DOTFILES="$HOME/config-files/dotfiles"
export KSC_GNOME_TERMINAL_SETTINGS="$HOME/config-files/misc-files/gnome_terminal_settings"
